[project]
name = "my_project"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
r = ">=4.4"
r-tidyverse = "*"
r-sf = "*"
r-terra = "*"
r-stars = "*"
r-tmap = "*"
r-mlr3 = "*"
r-remotes = "*"
r-knitr = "*"
r-rmarkdown = "*"
r-tidygraph = "*"
r-leaflet = "*"
r-plotly = "*"
r-curl = "*"
# See https://github.com/geocompx/geocompy/blob/main/environment.yml
bokeh = "*"
branca = "*"
cartopy = ">=0.22"
cython = "*"
fiona = ">=1.9"
folium = "*"
geopandas = ">=1.0.0"
geopy = "*"
geoviews = "*"
hvplot = "*"
jupyter = "*"
jupyterlab = "*"
mapclassify = "*"
matplotlib = "*"
nbformat = "*"
numpy = "*"
pandas = "*"
proj = "*"
pyogrio = "*"
quarto = "*"
rasterio = "*"
rasterstats = "*"
shapely = "*"
topojson = "*"
osmnx = "*"
contextily = "*"
richdem = "*"
