name: pixi-py

on:
  schedule:
    - cron: '0  21 * * 6'
  push:
    branches:
      - 'master'
      - 'main'
    paths:
      - 'pixi-py/**'

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            geocompr/geocompr
            ghcr.io/geocompx/pixi-py
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=pixi-py
            type=sha,prefix=pixi-py_
            type=schedule,pattern={{date 'YYYY-MM-DD'}},prefix=pixi-py_
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: pixi-py
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
          


