name: suggests

on:
  schedule:
    - cron: '0 03 * * 5' # everyday at 1am
  push:
    branches:
      - 'master'
      - 'main'
    paths:
      - 'suggests/**'

jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            geocompr/geocompr
            ghcr.io/geocompx/suggests
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=suggests
            type=sha,prefix=suggests_
            type=schedule,pattern={{date 'YYYY-MM-DD'}},prefix=suggests_
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: suggests
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "GITHUB_PAT=${{ secrets.GITHUB_TOKEN }}"
